/*
 * Copyright (c) 2010-2026. Axon Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.axonframework.messaging.eventhandling.configuration;

import org.jspecify.annotations.NonNull;
import org.axonframework.common.AxonConfigurationException;
import org.axonframework.common.configuration.ComponentBuilder;
import org.axonframework.messaging.core.Message;
import org.axonframework.messaging.core.MessageStream;
import org.axonframework.messaging.core.QualifiedName;
import org.axonframework.messaging.core.configuration.MessagingConfigurer;
import org.axonframework.messaging.core.unitofwork.ProcessingContext;
import org.axonframework.messaging.core.unitofwork.StubProcessingContext;
import org.axonframework.messaging.eventhandling.DelegatingEventHandlingComponent;
import org.axonframework.messaging.eventhandling.EventHandlingComponent;
import org.axonframework.messaging.eventhandling.EventMessage;
import org.axonframework.messaging.eventhandling.EventTestUtils;
import org.axonframework.messaging.eventhandling.SimpleEventHandlingComponent;
import org.axonframework.messaging.eventhandling.interception.InterceptingEventHandlingComponent;
import org.junit.jupiter.api.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Test class validating the {@link DefaultEventHandlingComponentsConfigurer} functionality.
 *
 * @author Mateusz Nowak
 * @since 5.0.0
 */
class DefaultEventHandlingComponentsConfigurerTest {

    private static final StubProcessingContext STUB_PROCESSING_CONTEXT = new StubProcessingContext();

    @Nested
    class SingleWithComponentTest {

        @Test
        void shouldCreateSingleComponentFromEventHandlingComponent() {
            //given
            ComponentBuilder<EventHandlingComponent> componentBuilder = cfg -> {
                SimpleEventHandlingComponent handlingComponent = SimpleEventHandlingComponent.create("test");
                handlingComponent.subscribe(new QualifiedName(String.class), (e, c) -> MessageStream.empty());
                return handlingComponent;
            };

            //when
            var componentsConfigurer = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("component", componentBuilder);
            var components = componentsConfigurer.toMap();

            //then
            assertThat(components).hasSize(1);
            assertThat(components).containsEntry("component", componentBuilder);
        }
    }

    @Nested
    class ManyWithComponentsTest {

        @Test
        void shouldCreateManyComponentsFromEventHandlingComponents() {
            // given
            ComponentBuilder<EventHandlingComponent> componentBuilder1 =
                    cfg -> SimpleEventHandlingComponent.create("component1");
            ComponentBuilder<EventHandlingComponent> componentBuilder2 =
                    cfg -> SimpleEventHandlingComponent.create("component2");
            ComponentBuilder<EventHandlingComponent> componentBuilder3 =
                    cfg -> SimpleEventHandlingComponent.create("component3");

            // when
            var componentsConfigurer = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("component1", componentBuilder1)
                    .declarative("component2", componentBuilder2)
                    .declarative("component3", componentBuilder3);
            var components = componentsConfigurer.toMap();

            // then
            assertThat(components).hasSize(3);
            assertThat(components.keySet()).containsExactly("component1", "component2", "component3");
            assertThat(components.values()).containsExactly(componentBuilder1, componentBuilder2, componentBuilder3);
        }

        @Test
        void shouldCreateManyComponentsWithAutoGeneratedIndexNames() {
            // given
            ComponentBuilder<EventHandlingComponent> componentBuilder1 =
                    cfg -> SimpleEventHandlingComponent.create("component1");
            ComponentBuilder<EventHandlingComponent> componentBuilder2 =
                    cfg -> SimpleEventHandlingComponent.create("component2");
            ComponentBuilder<EventHandlingComponent> componentBuilder3 =
                    cfg -> SimpleEventHandlingComponent.create("component3");

            // when
            var componentsConfigurer = new DefaultEventHandlingComponentsConfigurer()
                    .declarative(componentBuilder1)
                    .declarative(componentBuilder2)
                    .declarative(componentBuilder3);
            var components = componentsConfigurer.toMap();

            // then
            assertThat(components).hasSize(3);
            assertThat(components.keySet()).containsExactly("0", "1", "2");
            assertThat(components.values()).containsExactly(componentBuilder1, componentBuilder2, componentBuilder3);
        }
    }

    @Nested
    class NameValidationTest {

        @Test
        void shouldFailWhenDuplicateNameIsConfigured() {
            // given
            var testSubject = new DefaultEventHandlingComponentsConfigurer();

            // when / then
            assertThatThrownBy(() -> testSubject
                    .declarative("component", cfg -> SimpleEventHandlingComponent.create("component"))
                    .declarative("component", cfg -> SimpleEventHandlingComponent.create("other")))
                    .isInstanceOf(AxonConfigurationException.class)
                    .hasMessageContaining("already registered");
        }
    }

    @Nested
    class InterceptedTest {

        private final EventMessage sampleEvent = EventTestUtils.asEventMessage("payload");
        private final MessagingConfigurer configurer = MessagingConfigurer.create();

        @Test
        void singleInterceptorIsInvokedBeforeHandler() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> { invocationLog.add("handler"); return MessageStream.empty(); });

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .intercepted(cfg -> (msg, ctx, chain) -> { invocationLog.add("interceptor"); return chain.proceed(msg, ctx); })
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when
            builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("interceptor", "handler");
        }

        @Test
        void multipleInterceptorsAreInvokedInRegistrationOrder() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> { invocationLog.add("handler"); return MessageStream.empty(); });

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .intercepted(cfg -> (msg, ctx, chain) -> { invocationLog.add("first"); return chain.proceed(msg, ctx); })
                    .intercepted(cfg -> (msg, ctx, chain) -> { invocationLog.add("second"); return chain.proceed(msg, ctx); })
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when
            builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("first", "second", "handler");
        }

        @Test
        void noWrappingWhenNoInterceptorsRegistered() {
            // given
            var component = SimpleEventHandlingComponent.create("comp");

            // when
            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // then
            assertThat(builtComponent).isNotInstanceOf(InterceptingEventHandlingComponent.class);
        }

        @Test
        void allRegisteredComponentsAreWrapped() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var comp1 = SimpleEventHandlingComponent.create("comp1");
            comp1.subscribe(new QualifiedName(String.class),
                            (e, c) -> { invocationLog.add("handler1"); return MessageStream.empty(); });
            var comp2 = SimpleEventHandlingComponent.create("comp2");
            comp2.subscribe(new QualifiedName(String.class),
                            (e, c) -> { invocationLog.add("handler2"); return MessageStream.empty(); });

            var built = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp1", cfg -> comp1)
                    .declarative("comp2", cfg -> comp2)
                    .intercepted(cfg -> (msg, ctx, chain) -> { invocationLog.add("interceptor"); return chain.proceed(msg, ctx); })
                    .toMap();
            var cfg = configurer.build();

            // when
            built.get("comp1").build(cfg).handle(sampleEvent, STUB_PROCESSING_CONTEXT);
            built.get("comp2").build(cfg).handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("interceptor", "handler1", "interceptor", "handler2");
            assertThat(built.get("comp1").build(cfg)).isInstanceOf(InterceptingEventHandlingComponent.class);
            assertThat(built.get("comp2").build(cfg)).isInstanceOf(InterceptingEventHandlingComponent.class);
        }

        @Test
        void interceptorCanShortCircuitWithoutCallingChain() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> { invocationLog.add("handler"); return MessageStream.empty(); });

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .intercepted(cfg -> (msg, ctx, chain) -> { invocationLog.add("interceptor"); return MessageStream.empty(); })
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when
            builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("interceptor");
        }
    }

    @Nested
    class WithExceptionHandlerTest {

        private final EventMessage sampleEvent = EventTestUtils.asEventMessage("payload");
        private final MessagingConfigurer configurer = MessagingConfigurer.create();

        @Test
        void exceptionHandlerIsInvokedWhenHandlerThrows() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> MessageStream.failed(new RuntimeException("handler failed")));

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .withExceptionHandler((event, context, error) -> { invocationLog.add("exceptionHandler"); return MessageStream.empty(); })
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when
            builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("exceptionHandler");
        }

        @Test
        void exceptionHandlerCanSuppressException() {
            // given
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> MessageStream.failed(new RuntimeException("handler failed")));

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .withExceptionHandler((event, context, error) -> MessageStream.empty())
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when - exception handler returns normally, suppressing the error
            var result = builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(result.error()).isEmpty();
        }

        @Test
        void exceptionHandlerCanPropagateError() {
            // given
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> MessageStream.failed(new RuntimeException("original")));

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .withExceptionHandler((event, context, error) -> MessageStream.failed(new IOException("wrapped")))
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when - exception handler returns a failed stream, the error propagates
            var result = builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(result.error()).isPresent();
            assertThat(result.error().get()).isInstanceOf(IOException.class).hasMessage("wrapped");
        }

        @Test
        void exceptionHandlerUnexpectedThrowIsWrappedInFailedStream() {
            // given
            var component = SimpleEventHandlingComponent.create("comp");
            component.subscribe(new QualifiedName(String.class),
                                (e, c) -> MessageStream.failed(new RuntimeException("original")));

            var builtComponent = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp", cfg -> component)
                    .withExceptionHandler((event, context, error) -> { throw new RuntimeException("unexpected"); })
                    .toMap()
                    .get("comp")
                    .build(configurer.build());

            // when - exception handler throws unexpectedly, the thrown exception propagates as a failed stream
            var result = builtComponent.handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(result.error()).isPresent();
            assertThat(result.error().get()).isInstanceOf(RuntimeException.class).hasMessage("unexpected");
        }

        @Test
        void exceptionHandlerIsAppliedToAllComponents() {
            // given
            List<String> invocationLog = new ArrayList<>();
            var comp1 = SimpleEventHandlingComponent.create("comp1");
            comp1.subscribe(new QualifiedName(String.class),
                            (e, c) -> MessageStream.failed(new RuntimeException("fail1")));
            var comp2 = SimpleEventHandlingComponent.create("comp2");
            comp2.subscribe(new QualifiedName(String.class),
                            (e, c) -> MessageStream.failed(new RuntimeException("fail2")));

            var built = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("comp1", cfg -> comp1)
                    .declarative("comp2", cfg -> comp2)
                    .withExceptionHandler((event, context, error) -> { invocationLog.add(error.getMessage()); return MessageStream.empty(); })
                    .toMap();
            var cfg = configurer.build();

            // when
            built.get("comp1").build(cfg).handle(sampleEvent, STUB_PROCESSING_CONTEXT);
            built.get("comp2").build(cfg).handle(sampleEvent, STUB_PROCESSING_CONTEXT);

            // then
            assertThat(invocationLog).containsExactly("fail1", "fail2");
        }
    }

    @Nested
    class DecoratedTest {

        @Test
        void shouldDecorateAllComponents() {
            //given
            var component1 = SimpleEventHandlingComponent.create("component1");
            component1.subscribe(new QualifiedName(String.class), (e, c) -> MessageStream.empty());
            var component2 = SimpleEventHandlingComponent.create("component2");
            component2.subscribe(new QualifiedName(String.class), (e, c) -> MessageStream.empty());

            var componentsConfigurer = new DefaultEventHandlingComponentsConfigurer()
                    .declarative("component1", cfg -> component1)
                    .declarative("component2", cfg -> component2);

            //when
            var configuration = MessagingConfigurer.create().build();
            var decoratedConfigurer = componentsConfigurer.decorated((cfg, c) -> new SampleDecoration(c));
            var decoratedComponents = decoratedConfigurer.toMap()
                                                        .values()
                                                        .stream()
                                                        .map(builder -> builder.build(configuration))
                                                        .toList();

            //then
            assertThat(decoratedComponents).hasSize(2);

            SampleDecoration decoration1 = (SampleDecoration) decoratedComponents.get(0);
            SampleDecoration decoration2 = (SampleDecoration) decoratedComponents.get(1);

            EventMessage sampleMessage = EventTestUtils.asEventMessage("Message1");
            decoration1.handle(sampleMessage, STUB_PROCESSING_CONTEXT);
            decoration2.handle(sampleMessage, STUB_PROCESSING_CONTEXT);

            assertThat(decoration1.invoked).isTrue();
            assertThat(decoration2.invoked).isTrue();
        }

        static class SampleDecoration extends DelegatingEventHandlingComponent {

            AtomicBoolean invoked = new AtomicBoolean();

            public SampleDecoration(@NonNull EventHandlingComponent delegate) {
                super(delegate);
            }

            @Override
            public MessageStream.@NonNull Empty<Message> handle(@NonNull EventMessage event,
                                                                @NonNull ProcessingContext context) {
                invoked.set(true);
                return super.handle(event, context);
            }
        }
    }
}
